<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="José Vinueza">

<title>Tasa de desempleo ecuatoriana Noviembre 2022 - Septiembre 2025</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="desempleo doc final con indice_files/libs/clipboard/clipboard.min.js"></script>
<script src="desempleo doc final con indice_files/libs/quarto-html/quarto.js"></script>
<script src="desempleo doc final con indice_files/libs/quarto-html/popper.min.js"></script>
<script src="desempleo doc final con indice_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="desempleo doc final con indice_files/libs/quarto-html/anchor.min.js"></script>
<link href="desempleo doc final con indice_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="desempleo doc final con indice_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="desempleo doc final con indice_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="desempleo doc final con indice_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="desempleo doc final con indice_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="desempleo doc final con indice_files/libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet">

<script src="desempleo doc final con indice_files/libs/htmlwidgets-1.6.4.9000/htmlwidgets.js"></script>

<script src="desempleo doc final con indice_files/libs/jquery-1.11.1/jquery.min.js"></script>

<link href="desempleo doc final con indice_files/libs/dygraphs-1.1.1/dygraph.css" rel="stylesheet">

<script src="desempleo doc final con indice_files/libs/dygraphs-1.1.1/dygraph-combined.js"></script>

<script src="desempleo doc final con indice_files/libs/dygraphs-1.1.1/shapes.js"></script>

<script src="desempleo doc final con indice_files/libs/moment-2.29.4/moment.js"></script>

<script src="desempleo doc final con indice_files/libs/moment-timezone-0.2.5/moment-timezone-with-data.js"></script>

<script src="desempleo doc final con indice_files/libs/moment-fquarter-1.0.0/moment-fquarter.min.js"></script>

<script src="desempleo doc final con indice_files/libs/dygraphs-binding-1.1.1.7/dygraphs.js"></script>



</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#descarga-de-informes-mensuales-del-bce-compilación-y-limpieza-de-los-datos" id="toc-descarga-de-informes-mensuales-del-bce-compilación-y-limpieza-de-los-datos" class="nav-link active" data-scroll-target="#descarga-de-informes-mensuales-del-bce-compilación-y-limpieza-de-los-datos">1. Descarga de informes mensuales del BCE, compilación y limpieza de los datos</a></li>
  <li><a href="#gráfica-de-la-tasa-de-desempleo-ecuatoriano-para-el-período-noviembre-2022-a-septiembre-2025" id="toc-gráfica-de-la-tasa-de-desempleo-ecuatoriano-para-el-período-noviembre-2022-a-septiembre-2025" class="nav-link" data-scroll-target="#gráfica-de-la-tasa-de-desempleo-ecuatoriano-para-el-período-noviembre-2022-a-septiembre-2025">2. Gráfica de la tasa de desempleo ecuatoriano para el período noviembre 2022 a septiembre 2025</a></li>
  <li><a href="#gráfico-de-incrementos-y-decrementos-de-la-tasa-de-desempleo-ecuatoriano" id="toc-gráfico-de-incrementos-y-decrementos-de-la-tasa-de-desempleo-ecuatoriano" class="nav-link" data-scroll-target="#gráfico-de-incrementos-y-decrementos-de-la-tasa-de-desempleo-ecuatoriano">3. Gráfico de incrementos y decrementos de la tasa de desempleo ecuatoriano</a></li>
  <li><a href="#componentes-temporales-de-la-tasa-de-desempleo-ecuatoriano" id="toc-componentes-temporales-de-la-tasa-de-desempleo-ecuatoriano" class="nav-link" data-scroll-target="#componentes-temporales-de-la-tasa-de-desempleo-ecuatoriano">4. Componentes temporales de la tasa de desempleo ecuatoriano</a></li>
  <li><a href="#tendencia-de-la-tasa-de-desempleo" id="toc-tendencia-de-la-tasa-de-desempleo" class="nav-link" data-scroll-target="#tendencia-de-la-tasa-de-desempleo">4.1 Tendencia de la tasa de desempleo</a></li>
  <li><a href="#estacionalidad-de-la-tasa-de-desempleo" id="toc-estacionalidad-de-la-tasa-de-desempleo" class="nav-link" data-scroll-target="#estacionalidad-de-la-tasa-de-desempleo">4.2 Estacionalidad de la tasa de desempleo</a></li>
  <li><a href="#modelamiento-de-la-tasa-de-desempleo" id="toc-modelamiento-de-la-tasa-de-desempleo" class="nav-link" data-scroll-target="#modelamiento-de-la-tasa-de-desempleo">5. Modelamiento de la tasa de desempleo</a></li>
  <li><a href="#gráficos-de-autocorrelación-acf-y-autocorrelación-parcial-pacf" id="toc-gráficos-de-autocorrelación-acf-y-autocorrelación-parcial-pacf" class="nav-link" data-scroll-target="#gráficos-de-autocorrelación-acf-y-autocorrelación-parcial-pacf">5.1 Gráficos de autocorrelación (ACF) y autocorrelación Parcial (PACF)</a></li>
  <li><a href="#modelos-arima-vs-holt-winters-ets-y-prophet" id="toc-modelos-arima-vs-holt-winters-ets-y-prophet" class="nav-link" data-scroll-target="#modelos-arima-vs-holt-winters-ets-y-prophet">5.2 Modelos ARIMA vs Holt Winters (ETS) y Prophet</a></li>
  <li><a href="#análisis-de-parámetros-del-modelo-seleccionado-ets" id="toc-análisis-de-parámetros-del-modelo-seleccionado-ets" class="nav-link" data-scroll-target="#análisis-de-parámetros-del-modelo-seleccionado-ets">6. Análisis de parámetros del modelo seleccionado (ETS)</a></li>
  <li><a href="#validación-del-modelo-ets" id="toc-validación-del-modelo-ets" class="nav-link" data-scroll-target="#validación-del-modelo-ets">7. Validación del modelo (ETS)</a>
  <ul class="collapse">
  <li><a href="#error-absoluto-medio-mae" id="toc-error-absoluto-medio-mae" class="nav-link" data-scroll-target="#error-absoluto-medio-mae">7.1 Error absoluto medio (MAE)</a></li>
  <li><a href="#error-cuadrático-medio-rmse" id="toc-error-cuadrático-medio-rmse" class="nav-link" data-scroll-target="#error-cuadrático-medio-rmse">7.2 Error cuadrático medio (RMSE)</a></li>
  <li><a href="#gráfico-de-los-residuos-del-modelo" id="toc-gráfico-de-los-residuos-del-modelo" class="nav-link" data-scroll-target="#gráfico-de-los-residuos-del-modelo">7.3 Gráfico de los residuos del modelo</a></li>
  <li><a href="#acf-de-los-residuos-del-modelo" id="toc-acf-de-los-residuos-del-modelo" class="nav-link" data-scroll-target="#acf-de-los-residuos-del-modelo">7.4 ACF de los residuos del modelo</a></li>
  <li><a href="#test-de-box-ljung" id="toc-test-de-box-ljung" class="nav-link" data-scroll-target="#test-de-box-ljung">7.5 Test de Box-Ljung</a></li>
  <li><a href="#conclusiones-de-la-validación-del-modelo" id="toc-conclusiones-de-la-validación-del-modelo" class="nav-link" data-scroll-target="#conclusiones-de-la-validación-del-modelo">7.6 Conclusiones de la validación del modelo</a></li>
  </ul></li>
  <li><a href="#proyección-de-la-tasa-de-desempleo" id="toc-proyección-de-la-tasa-de-desempleo" class="nav-link" data-scroll-target="#proyección-de-la-tasa-de-desempleo">8. Proyección de la tasa de desempleo</a>
  <ul class="collapse">
  <li><a href="#gráfico-de-la-tasa-nacional-de-desempleo-en-conjunto-con-los-valores-proyectados-y-los-intervalos-de-confianza" id="toc-gráfico-de-la-tasa-nacional-de-desempleo-en-conjunto-con-los-valores-proyectados-y-los-intervalos-de-confianza" class="nav-link" data-scroll-target="#gráfico-de-la-tasa-nacional-de-desempleo-en-conjunto-con-los-valores-proyectados-y-los-intervalos-de-confianza">8.1 Gráfico de la tasa nacional de desempleo en conjunto con los valores proyectados y los intervalos de confianza</a></li>
  <li><a href="#gráfico-de-los-valores-proyectados-para-6-meses" id="toc-gráfico-de-los-valores-proyectados-para-6-meses" class="nav-link" data-scroll-target="#gráfico-de-los-valores-proyectados-para-6-meses">8.2 Gráfico de los valores proyectados para 6 meses</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Tasa de desempleo ecuatoriana Noviembre 2022 - Septiembre 2025</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>José Vinueza </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="descarga-de-informes-mensuales-del-bce-compilación-y-limpieza-de-los-datos" class="level2">
<h2 class="anchored" data-anchor-id="descarga-de-informes-mensuales-del-bce-compilación-y-limpieza-de-los-datos">1. Descarga de informes mensuales del BCE, compilación y limpieza de los datos</h2>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: center;">Mes</th>
<th style="text-align: center;">Periodo</th>
<th style="text-align: center;">Nacional</th>
<th style="text-align: center;">Urbano</th>
<th style="text-align: center;">Rural</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Noviembre 2022</td>
<td style="text-align: center;">cie202301</td>
<td style="text-align: center;">3.80</td>
<td style="text-align: center;">4.72</td>
<td style="text-align: center;">1.95</td>
</tr>
<tr class="even">
<td style="text-align: center;">Diciembre 2022</td>
<td style="text-align: center;">cie202301</td>
<td style="text-align: center;">3.19</td>
<td style="text-align: center;">4.20</td>
<td style="text-align: center;">1.29</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Enero 2023</td>
<td style="text-align: center;">cie202303</td>
<td style="text-align: center;">3.75</td>
<td style="text-align: center;">4.95</td>
<td style="text-align: center;">1.48</td>
</tr>
<tr class="even">
<td style="text-align: center;">Febrero 2023</td>
<td style="text-align: center;">cie202303</td>
<td style="text-align: center;">3.86</td>
<td style="text-align: center;">5.17</td>
<td style="text-align: center;">1.34</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Marzo 2023</td>
<td style="text-align: center;">cie202304</td>
<td style="text-align: center;">3.63</td>
<td style="text-align: center;">4.86</td>
<td style="text-align: center;">1.29</td>
</tr>
<tr class="even">
<td style="text-align: center;">Abril 2023</td>
<td style="text-align: center;">cie202305</td>
<td style="text-align: center;">4.02</td>
<td style="text-align: center;">5.36</td>
<td style="text-align: center;">1.44</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Mayo 2023</td>
<td style="text-align: center;">cie202306</td>
<td style="text-align: center;">3.20</td>
<td style="text-align: center;">4.10</td>
<td style="text-align: center;">1.48</td>
</tr>
<tr class="even">
<td style="text-align: center;">Junio 2023</td>
<td style="text-align: center;">cie202308</td>
<td style="text-align: center;">3.83</td>
<td style="text-align: center;">5.00</td>
<td style="text-align: center;">1.57</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Julio 2023</td>
<td style="text-align: center;">cie202308</td>
<td style="text-align: center;">3.71</td>
<td style="text-align: center;">4.95</td>
<td style="text-align: center;">1.30</td>
</tr>
<tr class="even">
<td style="text-align: center;">Agosto 2023</td>
<td style="text-align: center;">cie202309</td>
<td style="text-align: center;">3.48</td>
<td style="text-align: center;">4.54</td>
<td style="text-align: center;">1.44</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Septiembre 2023</td>
<td style="text-align: center;">cie202310</td>
<td style="text-align: center;">3.68</td>
<td style="text-align: center;">4.79</td>
<td style="text-align: center;">1.61</td>
</tr>
<tr class="even">
<td style="text-align: center;">Octubre 2023</td>
<td style="text-align: center;">cie202312</td>
<td style="text-align: center;">3.56</td>
<td style="text-align: center;">4.58</td>
<td style="text-align: center;">1.62</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Noviembre 2023</td>
<td style="text-align: center;">cie202312</td>
<td style="text-align: center;">3.46</td>
<td style="text-align: center;">4.77</td>
<td style="text-align: center;">0.96</td>
</tr>
<tr class="even">
<td style="text-align: center;">Diciembre 2023</td>
<td style="text-align: center;">cie202402</td>
<td style="text-align: center;">3.38</td>
<td style="text-align: center;">4.44</td>
<td style="text-align: center;">1.38</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Enero 2024</td>
<td style="text-align: center;">cie202402</td>
<td style="text-align: center;">3.92</td>
<td style="text-align: center;">5.39</td>
<td style="text-align: center;">1.27</td>
</tr>
<tr class="even">
<td style="text-align: center;">Febrero 2024</td>
<td style="text-align: center;">cie202404</td>
<td style="text-align: center;">4.24</td>
<td style="text-align: center;">5.51</td>
<td style="text-align: center;">1.86</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Marzo 2024</td>
<td style="text-align: center;">cie202404</td>
<td style="text-align: center;">3.76</td>
<td style="text-align: center;">5.19</td>
<td style="text-align: center;">1.04</td>
</tr>
<tr class="even">
<td style="text-align: center;">Abril 2024</td>
<td style="text-align: center;">cie202405</td>
<td style="text-align: center;">3.39</td>
<td style="text-align: center;">4.49</td>
<td style="text-align: center;">1.33</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Mayo 2024</td>
<td style="text-align: center;">cie202406</td>
<td style="text-align: center;">3.55</td>
<td style="text-align: center;">4.63</td>
<td style="text-align: center;">1.45</td>
</tr>
<tr class="even">
<td style="text-align: center;">Junio 2024</td>
<td style="text-align: center;">cie202407</td>
<td style="text-align: center;">3.14</td>
<td style="text-align: center;">4.14</td>
<td style="text-align: center;">1.28</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Julio 2024</td>
<td style="text-align: center;">cie202408</td>
<td style="text-align: center;">3.72</td>
<td style="text-align: center;">4.86</td>
<td style="text-align: center;">1.52</td>
</tr>
<tr class="even">
<td style="text-align: center;">Agosto 2024</td>
<td style="text-align: center;">cie202409</td>
<td style="text-align: center;">4.00</td>
<td style="text-align: center;">5.33</td>
<td style="text-align: center;">1.47</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Septiembre 2024</td>
<td style="text-align: center;">cie202410</td>
<td style="text-align: center;">3.69</td>
<td style="text-align: center;">4.94</td>
<td style="text-align: center;">1.33</td>
</tr>
<tr class="even">
<td style="text-align: center;">Octubre 2024</td>
<td style="text-align: center;">cie202411</td>
<td style="text-align: center;">3.54</td>
<td style="text-align: center;">4.70</td>
<td style="text-align: center;">1.26</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Noviembre 2024</td>
<td style="text-align: center;">cie202412</td>
<td style="text-align: center;">3.73</td>
<td style="text-align: center;">5.07</td>
<td style="text-align: center;">1.27</td>
</tr>
<tr class="even">
<td style="text-align: center;">Diciembre 2024</td>
<td style="text-align: center;">cie202501</td>
<td style="text-align: center;">2.69</td>
<td style="text-align: center;">3.61</td>
<td style="text-align: center;">1.03</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Enero 2025</td>
<td style="text-align: center;">cie202502</td>
<td style="text-align: center;">3.82</td>
<td style="text-align: center;">5.07</td>
<td style="text-align: center;">1.62</td>
</tr>
<tr class="even">
<td style="text-align: center;">Febrero 2025</td>
<td style="text-align: center;">cie202503</td>
<td style="text-align: center;">3.82</td>
<td style="text-align: center;">5.07</td>
<td style="text-align: center;">1.62</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Marzo 2025</td>
<td style="text-align: center;">cie202505</td>
<td style="text-align: center;">3.31</td>
<td style="text-align: center;">4.25</td>
<td style="text-align: center;">1.59</td>
</tr>
<tr class="even">
<td style="text-align: center;">Abril 2025</td>
<td style="text-align: center;">cie202505</td>
<td style="text-align: center;">3.64</td>
<td style="text-align: center;">4.67</td>
<td style="text-align: center;">1.65</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Mayo 2025</td>
<td style="text-align: center;">cie202506</td>
<td style="text-align: center;">4.10</td>
<td style="text-align: center;">5.20</td>
<td style="text-align: center;">1.80</td>
</tr>
<tr class="even">
<td style="text-align: center;">Junio 2025</td>
<td style="text-align: center;">cie202507</td>
<td style="text-align: center;">3.50</td>
<td style="text-align: center;">4.50</td>
<td style="text-align: center;">1.60</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Julio 2025</td>
<td style="text-align: center;">cie202509</td>
<td style="text-align: center;">3.28</td>
<td style="text-align: center;">4.23</td>
<td style="text-align: center;">1.38</td>
</tr>
<tr class="even">
<td style="text-align: center;">Agosto 2025</td>
<td style="text-align: center;">cie202509</td>
<td style="text-align: center;">3.58</td>
<td style="text-align: center;">4.86</td>
<td style="text-align: center;">1.14</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Septiembre 2025</td>
<td style="text-align: center;">cie202510</td>
<td style="text-align: center;">3.19</td>
<td style="text-align: center;">4.07</td>
<td style="text-align: center;">1.53</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>En esta sección se presentan los datos obtenidos de los <strong>informes del Banco Central del Ecuador</strong>, disponibles en su portal en formato PDF. El propósito de este reporte automatizado es <strong>descargar dichos informes, almacenarlos para futuras consultas, extraer la tasa de desempleo, depurar la información y procesarla</strong> de manera sistemática. El cuadro mostrado constituye la evidencia del cumplimiento de cada uno de estos pasos.</p>
<p>Para referencia, uno de los informes del BCE puede descargarse en el siguiente enlace: <a href="https://contenido.bce.fin.ec/documentos/Estadisticas/SectorReal/Previsiones/IndCoyuntura/CifrasEconomicas/cie202510.pdf">Informe BCE – Cifras Económicas, octubre 2025</a></p>
<p>El código utilizado para la elaboración de este reporte y el análisis de los datos se encuentra disponible en GitHub: <a href="https://github.com/josevrz/Tasa-de-desempleo">Repositorio Tasa de desempleo</a></p>
</section>
<section id="gráfica-de-la-tasa-de-desempleo-ecuatoriano-para-el-período-noviembre-2022-a-septiembre-2025" class="level2">
<h2 class="anchored" data-anchor-id="gráfica-de-la-tasa-de-desempleo-ecuatoriano-para-el-período-noviembre-2022-a-septiembre-2025">2. Gráfica de la tasa de desempleo ecuatoriano para el período noviembre 2022 a septiembre 2025</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="desempleo-doc-final-con-indice_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>En el presente gráfico podemos observar que septiembre 2025 revela un comportamiento mixto en los sectores:</p>
<ol type="1">
<li><p>La tasa nacional descendió a 3.2%, consolidando una tendencia de mejora respecto a meses anteriores.</p></li>
<li><p>La tasa urbana también disminuyó, ubicándose en 4.1%, lo que sugiere una recuperación parcial del empleo formal.</p></li>
<li><p>En contraste, la tasa rural se incrementó levemente a 1.5%, posiblemente reflejando ajustes estacionales o fricciones en el empleo agrícola.</p></li>
</ol>
<p>Con respecto a la comparación con referentes históricos:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Referente histórico</th>
<th>Valor (%)</th>
<th>Observación</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Crisis 1999</td>
<td>14.4</td>
<td>Muy por encima del nivel actual; no hay señales de crisis</td>
</tr>
<tr class="even">
<td>Máximo histórico</td>
<td>6.5 (dic. 2009)</td>
<td>No se ha superado en ningún sector</td>
</tr>
<tr class="odd">
<td>Promedio histórico</td>
<td>4.3 (2007–2025)</td>
<td>La tasa nacional está <strong>por debajo</strong>, lo que indica estabilidad</td>
</tr>
<tr class="even">
<td>Mínimo histórico</td>
<td>2.7 (dic. 2024)</td>
<td>La tasa nacional se mantiene cerca</td>
</tr>
</tbody>
</table>
<p>La tasa nacional actual (3.2%) se ubica <strong>por debajo del promedio histórico</strong>, lo que sugiere que <strong>no existe deterioro estructural ni coyuntural</strong>. Este nivel es consistente con una economía que opera dentro de márgenes saludables de fricción laboral.</p>
<p>Desde la teoría económica, el desempleo puede analizarse como una variable que refleja tanto ciclos económicos como estructuras de mercado laboral. Según John Maynard Keynes, el desempleo puede persistir incluso en equilibrio si la demanda agregada es insuficiente, lo que justifica la intervención estatal para estimular el empleo.</p>
<p>En este caso, los niveles actuales no sugieren insuficiencia de demanda, sino una estabilidad estructural, donde las tasas se mantienen dentro de rangos esperables y no se observan presiones críticas.</p>
<p>Si bien existen otras variables dentro del campo macroeconómico y social con las que realizar comparaciones con el desempleo como por ejemplo: <strong>PIB</strong> (Ley de Okun) , <strong>Inflación</strong> (Curva de Phillips), <strong>Subempleo, pobreza, migración, criminalidad,</strong> el propósito de este análisis es <strong>univariado</strong>, centrado exclusivamente en el comportamiento de la <strong>tasa de desempleo</strong> a lo largo del tiempo. Esto permite una lectura clara y directa de la evolución laboral sin introducir complejidades multivariadas que serán abordadas en futuros trabajos.</p>
</section>
<section id="gráfico-de-incrementos-y-decrementos-de-la-tasa-de-desempleo-ecuatoriano" class="level2">
<h2 class="anchored" data-anchor-id="gráfico-de-incrementos-y-decrementos-de-la-tasa-de-desempleo-ecuatoriano">3. Gráfico de incrementos y decrementos de la tasa de desempleo ecuatoriano</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="desempleo-doc-final-con-indice_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El gráfico presenta la evolución de los cambios mensuales en la tasa de desempleo para los sectores nacional, urbano y rural, permitiendo identificar los momentos de mayor variación en la dinámica laboral entre noviembre de 2023 y septiembre de 2025.</p>
<p>En el sector nacional, el mayor incremento se registró en enero de 2025, con un aumento de 1.13 puntos porcentuales, mientras que la mayor reducción ocurrió en diciembre de 2024, con una caída de 1.04 puntos. Este comportamiento refleja una fuerte oscilación en el cambio de año, posiblemente asociada a ajustes estacionales o administrativos.</p>
<p>En el sector rural, el incremento más alto fue de 0.59 puntos en febrero de 2024, seguido por una disminución significativa de 0.82 puntos en marzo del mismo año, lo que sugiere una dinámica agrícola o de ocupación informal con alta sensibilidad estacional.</p>
<p>En el sector urbano, se observa la mayor volatilidad: el incremento más pronunciado fue de 1.46 puntos en enero de 2025, y la reducción más fuerte también fue de 1.46 puntos en diciembre de 2024, lo que indica una reversión abrupta en la dinámica del empleo formal urbano.</p>
<p>Estos valores extremos permiten identificar meses críticos en la evolución del desempleo, donde se concentran los mayores ajustes. La simetría entre diciembre 2024 y enero 2025 en los sectores nacional y urbano sugiere un efecto de transición anual, posiblemente vinculado a:</p>
<ul>
<li><p>Finalización y renovación de contratos públicos y privados.</p></li>
<li><p>Cambios en políticas de empleo o presupuestos institucionales.</p></li>
<li><p>Fricciones estacionales propias del mercado laboral ecuatoriano.</p></li>
<li><p>El comportamiento rural, en cambio, muestra picos más suaves y desplazados, lo que es consistente con una estructura laboral menos formal y más dependiente de ciclos agrícolas.</p></li>
</ul>
</section>
<section id="componentes-temporales-de-la-tasa-de-desempleo-ecuatoriano" class="level2">
<h2 class="anchored" data-anchor-id="componentes-temporales-de-la-tasa-de-desempleo-ecuatoriano">4. Componentes temporales de la tasa de desempleo ecuatoriano</h2>
<p>A partir de este punto se trabaja con la tasa nacional.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="desempleo-doc-final-con-indice_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="tendencia-de-la-tasa-de-desempleo" class="level2">
<h2 class="anchored" data-anchor-id="tendencia-de-la-tasa-de-desempleo">4.1 Tendencia de la tasa de desempleo</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="desempleo-doc-final-con-indice_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El gráfico muestra la evolución de la tasa de desempleo nacional junto con su tendencia suavizada. Se observa que los valores fluctúan alrededor de un nivel medio sin una dirección persistente al alza o a la baja. Este comportamiento sugiere que la serie no presenta una tendencia marcada y que su dinámica es compatible con una serie estacionaria, donde las variaciones se mantienen acotadas y centradas en torno a un promedio estable.</p>
<p>Para confirmar formalmente la estacionariedad, es apropiado aplicar pruebas como el test de Dickey-Fuller aumentado (ADF). Este contraste permite verificar si la serie contiene una raíz unitaria (indicativa de no estacionariedad) o si, por el contrario, las fluctuaciones se mantienen alrededor de un valor constante con varianza estable.</p>
<p>Hipótesis nula (H0): la serie tiene raíz unitaria → no es estacionaria.</p>
<p>Hipótesis alternativa (H1): la serie es estacionaria.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Augmented Dickey-Fuller Test

data:  com$Nacional
Dickey-Fuller = -4.8413, Lag order = 3, p-value = 0.01
alternative hypothesis: stationary</code></pre>
</div>
</div>
<p>El test arrojó un valor p-value de 0.01 el cual es menor a 0,05 por lo que se rechaza la hipótesis nula, se concluye que la serie es estacionaria, lo que respalda la interpretación visual del gráfico.</p>
<p>La idea de estacionariedad es central en la econometría de series de tiempo. Como señalaba <strong>Clive Granger</strong>, premio Nobel de Economía, las series económicas suelen mostrar fluctuaciones alrededor de un equilibrio de largo plazo, y la estacionariedad es condición necesaria para aplicar modelos predictivos robustos como ARIMA.</p>
</section>
<section id="estacionalidad-de-la-tasa-de-desempleo" class="level2">
<h2 class="anchored" data-anchor-id="estacionalidad-de-la-tasa-de-desempleo">4.2 Estacionalidad de la tasa de desempleo</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "2022-11-01" "2022-12-01" "2023-01-01" "2023-02-01" "2023-03-01"
[6] "2023-04-01"</code></pre>
</div>
<div class="cell-output-display">
<div class="dygraphs html-widget html-fill-item" id="htmlwidget-97f1849c92500344f5c9" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-97f1849c92500344f5c9">{"x":{"attrs":{"title":"Estacionalidad tasa de desempleo","labels":["month","V1"],"legend":"auto","retainDateWindow":false,"axes":{"x":{"pixelsPerLabel":60}}},"scale":"monthly","annotations":[],"shadings":[],"events":[],"format":"date","data":[["2022-11-01T00:00:00.000Z","2022-12-01T00:00:00.000Z","2023-01-01T00:00:00.000Z","2023-02-01T00:00:00.000Z","2023-03-01T00:00:00.000Z","2023-04-01T00:00:00.000Z","2023-05-01T00:00:00.000Z","2023-06-01T00:00:00.000Z","2023-07-01T00:00:00.000Z","2023-08-01T00:00:00.000Z","2023-09-01T00:00:00.000Z","2023-10-01T00:00:00.000Z","2023-11-01T00:00:00.000Z","2023-12-01T00:00:00.000Z","2024-01-01T00:00:00.000Z","2024-02-01T00:00:00.000Z","2024-03-01T00:00:00.000Z","2024-04-01T00:00:00.000Z","2024-05-01T00:00:00.000Z","2024-06-01T00:00:00.000Z","2024-07-01T00:00:00.000Z","2024-08-01T00:00:00.000Z","2024-09-01T00:00:00.000Z","2024-10-01T00:00:00.000Z","2024-11-01T00:00:00.000Z","2024-12-01T00:00:00.000Z","2025-01-01T00:00:00.000Z","2025-02-01T00:00:00.000Z","2025-03-01T00:00:00.000Z","2025-04-01T00:00:00.000Z","2025-05-01T00:00:00.000Z","2025-06-01T00:00:00.000Z","2025-07-01T00:00:00.000Z","2025-08-01T00:00:00.000Z","2025-09-01T00:00:00.000Z"],[0.01800347222222202,-0.5538715277777781,0.2969618055555557,0.4638368055555556,-0.02303819444444462,-0.2240798611111114,-0.2334548611111109,-0.1115798611111109,0.1273784722222225,0.1517534722222225,0.1042534722222222,-0.01616319444444444,0.01800347222222202,-0.5538715277777781,0.2969618055555557,0.4638368055555556,-0.02303819444444462,-0.2240798611111114,-0.2334548611111109,-0.1115798611111109,0.1273784722222225,0.1517534722222225,0.1042534722222222,-0.01616319444444444,0.01800347222222202,-0.5538715277777781,0.2969618055555557,0.4638368055555556,-0.02303819444444462,-0.2240798611111114,-0.2334548611111109,-0.1115798611111109,0.1273784722222225,0.1517534722222225,0.1042534722222222]]},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<p>El gráfico de estacionalidad evidencia que los meses de febrero concentran los mayores picos de desempleo, mientras que en diciembre se registran los valores más bajos. Este patrón refleja un comportamiento recurrente en el mercado laboral ecuatoriano:</p>
<p>En diciembre, la tasa de desempleo disminuye debido al aumento de la demanda laboral asociada a las festividades de fin de año, caracterizadas por contrataciones temporales en comercio, servicios y actividades vinculadas al consumo estacional.</p>
<p>En febrero, una vez concluido el periodo festivo y finalizados muchos contratos temporales, el desempleo tiende a incrementarse, generando el pico estacional más alto del año.</p>
<p>Este comportamiento es consistente con la teoría de las fluctuaciones estacionales en series de tiempo económicas, donde ciertos meses concentran variaciones recurrentes por factores institucionales y sociales. La dinámica diciembre–febrero puede interpretarse como un ciclo de contratación y desvinculación temporal, propio de economías con alta informalidad y fuerte dependencia del comercio estacional.</p>
<p>Desde una perspectiva teórica, este patrón se relaciona con lo que Keynes denominaba la demanda efectiva: el empleo depende de la capacidad de la economía para sostener la demanda agregada. En diciembre, la demanda se expande por el consumo festivo; en febrero, se contrae, generando un ajuste en el empleo.</p>
</section>
<section id="modelamiento-de-la-tasa-de-desempleo" class="level2">
<h2 class="anchored" data-anchor-id="modelamiento-de-la-tasa-de-desempleo">5. Modelamiento de la tasa de desempleo</h2>
</section>
<section id="gráficos-de-autocorrelación-acf-y-autocorrelación-parcial-pacf" class="level2">
<h2 class="anchored" data-anchor-id="gráficos-de-autocorrelación-acf-y-autocorrelación-parcial-pacf">5.1 Gráficos de autocorrelación (ACF) y autocorrelación Parcial (PACF)</h2>
<p>El <strong>ACF</strong> y el <strong>PACF</strong> se utilizan para analizar la dependencia temporal de una serie respecto a sus valores rezagados. El ACF muestra la <strong>correlación global</strong> entre los valores actuales y los de periodos anteriores, mientras que el PACF refleja la <strong>correlación directa</strong> con un rezago específico, eliminando la influencia de los rezagos intermedios.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="desempleo-doc-final-con-indice_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Los gráficos de Autocorrelación (ACF) y Autocorrelación Parcial (PACF) permiten identificar la dependencia temporal de la serie y orientar la selección de modelos ARIMA:</p>
<p>ACF: mide la correlación total entre los valores actuales y sus rezagos. En este caso, el rezago 1 es significativo, lo que indica la existencia de autocorrelación inmediata en la serie.</p>
<p>PACF: mide la correlación directa entre los valores presentes y un rezago específico, eliminando la influencia de rezagos intermedios. Se observa que el rezago 4 es significativo y negativo, lo que sugiere que valores altos de la tasa de desempleo hace cuatro periodos tienden a asociarse con valores más bajos en el presente (y viceversa). La diferencia clave respecto a la ACF es que la PACF cancela las influencias indirectas, mostrando únicamente la relación neta.</p>
<p>Dado que previamente se verificó la estacionariedad de la serie nacional, los resultados de la ACF y PACF orientan la construcción de modelos ARIMA:</p>
<p>Se consideran los modelos ARIMA(4,0,0) y ARIMA(4,0,1), que incorporan la autocorrelación de corto plazo y el efecto del rezago 4.</p>
<p>Se incluirá también un modelo Holt-Winters multiplicativo, adecuado para series con estacionalidad proporcional.</p>
<p>Finalmente, se probará el modelo Prophet, desarrollado por Meta, que utiliza descomposición aditiva con componentes de tendencia, estacionalidad y efectos de calendario (https://facebook.github.io/prophet/docs/quick_start.html#r-apil).</p>
</section>
<section id="modelos-arima-vs-holt-winters-ets-y-prophet" class="level2">
<h2 class="anchored" data-anchor-id="modelos-arima-vs-holt-winters-ets-y-prophet">5.2 Modelos ARIMA vs Holt Winters (ETS) y Prophet</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="desempleo-doc-final-con-indice_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="desempleo-doc-final-con-indice_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: center;">Modelo</th>
<th style="text-align: center;">AIC</th>
<th style="text-align: center;">BIC</th>
<th style="text-align: center;">MAE</th>
<th style="text-align: center;">RMSE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">ARIMA(4,0,1)</td>
<td style="text-align: center;">20.80</td>
<td style="text-align: center;">31.69</td>
<td style="text-align: center;">0.2118</td>
<td style="text-align: center;">0.2622</td>
</tr>
<tr class="even">
<td style="text-align: center;">AR(4)</td>
<td style="text-align: center;">20.37</td>
<td style="text-align: center;">29.70</td>
<td style="text-align: center;">0.2141</td>
<td style="text-align: center;">0.2690</td>
</tr>
<tr class="odd">
<td style="text-align: center;">ETS(M,M,M)</td>
<td style="text-align: center;">NA</td>
<td style="text-align: center;">NA</td>
<td style="text-align: center;">0.0520</td>
<td style="text-align: center;">0.0652</td>
</tr>
<tr class="even">
<td style="text-align: center;">Prophet</td>
<td style="text-align: center;">NA</td>
<td style="text-align: center;">NA</td>
<td style="text-align: center;">0.1225</td>
<td style="text-align: center;">0.1589</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Como se puede apreciar el modelo Holt Winters (ETS) tiene el mejor ajuste de la serie de tiempo ya que tiene el menor MAE y RMSE, lo que indica que sus errores son más pequeños y consistentes.</p>
<p>Cabe destacar que Prophet tiene buen desempeño, pero no supera a ETS.</p>
</section>
<section id="análisis-de-parámetros-del-modelo-seleccionado-ets" class="level1">
<h1>6. Análisis de parámetros del modelo seleccionado (ETS)</h1>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">modelo_ets$par</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">alpha</td>
<td style="text-align: center;">0.0121259</td>
</tr>
<tr class="even">
<td style="text-align: left;">beta</td>
<td style="text-align: center;">0.0121235</td>
</tr>
<tr class="odd">
<td style="text-align: left;">gamma</td>
<td style="text-align: center;">0.0001502</td>
</tr>
<tr class="even">
<td style="text-align: left;">l</td>
<td style="text-align: center;">3.7157247</td>
</tr>
<tr class="odd">
<td style="text-align: left;">b</td>
<td style="text-align: center;">0.9986766</td>
</tr>
<tr class="even">
<td style="text-align: left;">s0</td>
<td style="text-align: center;">0.9742648</td>
</tr>
<tr class="odd">
<td style="text-align: left;">s1</td>
<td style="text-align: center;">0.9891271</td>
</tr>
<tr class="even">
<td style="text-align: left;">s2</td>
<td style="text-align: center;">1.0230976</td>
</tr>
<tr class="odd">
<td style="text-align: left;">s3</td>
<td style="text-align: center;">1.0164375</td>
</tr>
<tr class="even">
<td style="text-align: left;">s4</td>
<td style="text-align: center;">0.9660464</td>
</tr>
<tr class="odd">
<td style="text-align: left;">s5</td>
<td style="text-align: center;">1.0232978</td>
</tr>
<tr class="even">
<td style="text-align: left;">s6</td>
<td style="text-align: center;">1.0165032</td>
</tr>
<tr class="odd">
<td style="text-align: left;">s7</td>
<td style="text-align: center;">0.9720832</td>
</tr>
<tr class="even">
<td style="text-align: left;">s8</td>
<td style="text-align: center;">1.0942549</td>
</tr>
<tr class="odd">
<td style="text-align: left;">s9</td>
<td style="text-align: center;">1.0637490</td>
</tr>
<tr class="even">
<td style="text-align: left;">s10</td>
<td style="text-align: center;">0.8462161</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>α (alpha): suavizamiento del nivel</p>
<p>β (beta): suavizamiento de la tendencia</p>
<p>γ (gamma): suavizamiento de la estacionalidad</p>
<p>l: Nivel inicial (intercepto)</p>
<p>b: Tendencia inicial (pendiente).</p>
<p>Los valores s0 a s10 indican el efecto estacional relativo de cada mes (noviembre a octubre)</p>
<ul>
<li><p>α al ser un valor bajo indica que el modelo promedia los datos a lo largo de un período más prolongado, haciendo el pronóstico menos sensible a los cambios recientes.</p></li>
<li><p>β al ser un valor bajo considera a la tendencia constante.</p></li>
<li><p>γ indica una estacionalidad más estable y consistente a lo largo del tiempo.</p></li>
<li><p>I representa el valor base de la serie de tiempo en el momento de inicio (justo antes del primer período). Es el valor de partida para el componente de nivel del pronóstico.</p></li>
<li><p>b representa la pendiente de la serie en el momento de inicio. Indica la tasa de crecimiento o decrecimiento de la serie al principio del período de pronóstico.</p></li>
<li><p>Los valores de s0 a s10 se verán de mejor manera en el siguiente gráfico.</p></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="desempleo-doc-final-con-indice_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El modelo ETS es muy conservador en sus ajustes de nivel y tendencia (α y β muy bajos).</p>
<p>La estacionalidad es suave pero presente, con algunos meses claramente más altos o bajos.</p>
<p>El mes que presenta mayor peso en el modelo es s8 (julio)</p>
<p>El mes que presenta la menor ponderación en el modelo es s10 (septiembre)</p>
<p>El modelo está capturando patrones estables y cíclicos, indicando que los picos detectados no son necesariamente estructurales, sino parte del patrón cíclico, lo que se refleja en su buen desempeño en MAE y RMSE.</p>
</section>
<section id="validación-del-modelo-ets" class="level1">
<h1>7. Validación del modelo (ETS)</h1>
<section id="error-absoluto-medio-mae" class="level2">
<h2 class="anchored" data-anchor-id="error-absoluto-medio-mae">7.1 Error absoluto medio (MAE)</h2>
<p>Mide la magnitud promedio de los errores de predicción, el objetivo del MAE es comunicar el <strong>error promedio en unidades reales</strong> (como puntos porcentuales en este caso).</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>La media de los residuos de la tasa de desempleo es: 0.052 </code></pre>
</div>
</div>
</section>
<section id="error-cuadrático-medio-rmse" class="level2">
<h2 class="anchored" data-anchor-id="error-cuadrático-medio-rmse">7.2 Error cuadrático medio (RMSE)</h2>
<p>Se calcula como la raíz cuadrada de la media de las diferencias al cuadrado entre las predicciones y los valores observados. Un RMSE bajo indica que el modelo se ajusta mejor a los datos, mientras que un RMSE alto significa que las predicciones son menos precisas.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>RMSE: 0.0652 </code></pre>
</div>
</div>
</section>
<section id="gráfico-de-los-residuos-del-modelo" class="level2">
<h2 class="anchored" data-anchor-id="gráfico-de-los-residuos-del-modelo">7.3 Gráfico de los residuos del modelo</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="desempleo-doc-final-con-indice_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El gráfico de residuos muestra que:</p>
<p>Residuos centrados en cero: la mayoría de los errores se distribuyen alrededor de la línea base, lo que indica ausencia de sesgo sistemático en las proyecciones.</p>
<p>Bandas de ±2σ: casi todos los residuos se mantienen dentro de las bandas de confianza. Solo se observa un pico aislado en 2023 que supera este umbral.</p>
<p>Variabilidad moderada: no hay acumulación de picos ni patrones persistentes de desviación, lo que sugiere que el modelo captura adecuadamente la dinámica de la serie.</p>
<p>El pico en 2023 debe interpretarse como un evento atípico puntual (anomalía), más que como una falla estructural del modelo. En series económicas es normal que existan valores extremos asociados a shocks coyunturales.</p>
<p>La consistencia del resto de los residuos dentro de ±2σ confirma que el modelo mantiene un buen ajuste en la mayor parte del periodo.</p>
</section>
<section id="acf-de-los-residuos-del-modelo" class="level2">
<h2 class="anchored" data-anchor-id="acf-de-los-residuos-del-modelo">7.4 ACF de los residuos del modelo</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="desempleo-doc-final-con-indice_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El análisis del gráfico de autocorrelación (ACF) de los residuos muestra que el <strong>lag 1 aparece significativo</strong>, lo cual es esperable dado que refleja la correlación inmediata de la serie consigo misma y no constituye evidencia de falla del modelo. Asimismo, se observa cierta <strong>significación en el lag 4</strong>, pero este comportamiento no invalida el modelo ETS(M,M,M), ya que, a diferencia de los modelos ARIMA, el ETS no incorpora explícitamente rezagos autorregresivos en su estructura. En consecuencia, la presencia de correlaciones en algunos rezagos es compatible con la lógica del ETS, que se centra en <strong>error, tendencia y estacionalidad multiplicativa</strong>, más que en la parametrización de dependencias temporales. Por ello, la autocorrelación observada en el lag 4 debe interpretarse como una <strong>señal débil</strong> y no como evidencia de un problema estructural en el ajuste del modelo.</p>
</section>
<section id="test-de-box-ljung" class="level2">
<h2 class="anchored" data-anchor-id="test-de-box-ljung">7.5 Test de Box-Ljung</h2>
<p>Este test evalúa si los residuos del modelo presentan autocorrelación significativa, es decir, si hay patrones temporales no capturados por el modelo.</p>
<ul>
<li>H₀ (nula): Los residuos son ruido blanco (no hay autocorrelación).</li>
<li>H₁ (alternativa): Los residuos presentan autocorrelación.</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Box-Ljung test

data:  residuos
X-squared = 20.814, df = 12, p-value = 0.05317</code></pre>
</div>
</div>
<p>El p-value es de 0.05317 el cual es mayor a 0.05, por lo tanto no se rechaza la hipótesis nula, el modelo ETS está capturando bien la estructura de la serie.</p>
</section>
<section id="conclusiones-de-la-validación-del-modelo" class="level2">
<h2 class="anchored" data-anchor-id="conclusiones-de-la-validación-del-modelo">7.6 Conclusiones de la validación del modelo</h2>
<p><strong>1. Residuos centrados en cero</strong> La mayoría de los residuos oscilan alrededor de la línea base, lo que indica que el modelo no presenta sesgo sistemático: no tiende a sobrestimar ni subestimar de forma persistente.</p>
<p><strong>2. Residuos dentro de las bandas ±2σ</strong> Casi todos los puntos se encuentran dentro del rango esperado definido por ±2 desviaciones estándar. Se observa un único pico que supera este rango en 2023, coincidente con un evento atípico en el mercado laboral, lo que sugiere una anomalía puntual y no una falla estructural del modelo.</p>
<p><strong>3. Variabilidad moderada</strong> Aunque existen fluctuaciones, no se identifican picos extremos ni patrones persistentes. Esto indica que el modelo captura adecuadamente la dinámica de la serie sin dejar errores sistemáticos relevantes.</p>
<p><strong>4. Autocorrelación débil en los residuos</strong> El gráfico de ACF muestra que el lag 1 es significativo, lo cual es esperable porque refleja la correlación inmediata de la serie consigo misma. También se observa cierta significación en el lag 4, lo que sugiere una dependencia temporal débil. Sin embargo, el test de Box-Ljung arroja un p-value de 0.05317, lo que indica que no se rechaza la hipótesis nula de independencia de los residuos al nivel de significancia convencional (α = 0.05). En consecuencia, la autocorrelación detectada es leve y no compromete la validez del modelo ETS, que se centra en error, tendencia y estacionalidad multiplicativa, sin incorporar explícitamente rezagos autorregresivos como los modelos ARIMA.</p>
<p><strong>5. Solidez del ajuste y validez para proyección</strong> El modelo ETS(M,M,M) muestra un ajuste robusto: los residuos son centrados, independientes y dentro de un rango esperable. No hay evidencia de errores sistemáticos ni de autocorrelación fuerte, lo que valida su uso para proyecciones confiables.</p>
<p><strong>6. Indicadores de precisión Los valores de MAE y RMSE</strong> muestran diferencias promedio pequeñas entre los valores observados de la tasa nacional y sus respectivas proyecciones, lo que reafirma la calidad del ajuste.</p>
</section>
</section>
<section id="proyección-de-la-tasa-de-desempleo" class="level1">
<h1>8. Proyección de la tasa de desempleo</h1>
<section id="gráfico-de-la-tasa-nacional-de-desempleo-en-conjunto-con-los-valores-proyectados-y-los-intervalos-de-confianza" class="level2">
<h2 class="anchored" data-anchor-id="gráfico-de-la-tasa-nacional-de-desempleo-en-conjunto-con-los-valores-proyectados-y-los-intervalos-de-confianza">8.1 Gráfico de la tasa nacional de desempleo en conjunto con los valores proyectados y los intervalos de confianza</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="desempleo-doc-final-con-indice_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>En el gráfico se puede observar la serie histórica de la tasa nacional de desempleo y la proyección obtenida con sus respectivos intervalos de confianza al 80 y 95 % de confianza, como se puede apreciar la proyección sigue el mismo patrón de de la serie.</p>
</section>
<section id="gráfico-de-los-valores-proyectados-para-6-meses" class="level2">
<h2 class="anchored" data-anchor-id="gráfico-de-los-valores-proyectados-para-6-meses">8.2 Gráfico de los valores proyectados para 6 meses</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="desempleo-doc-final-con-indice_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Fecha</th>
<th style="text-align: center;">Proyeccion</th>
<th style="text-align: center;">IC_80_inf</th>
<th style="text-align: center;">IC_80_sup</th>
<th style="text-align: center;">IC_95_inf</th>
<th style="text-align: center;">IC_95_sup</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">2025-10-01</td>
<td style="text-align: center;">3.44</td>
<td style="text-align: center;">3.05</td>
<td style="text-align: center;">3.82</td>
<td style="text-align: center;">2.85</td>
<td style="text-align: center;">4.03</td>
</tr>
<tr class="even">
<td style="text-align: center;">2025-11-01</td>
<td style="text-align: center;">3.57</td>
<td style="text-align: center;">3.16</td>
<td style="text-align: center;">3.98</td>
<td style="text-align: center;">2.94</td>
<td style="text-align: center;">4.19</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2025-12-01</td>
<td style="text-align: center;">2.97</td>
<td style="text-align: center;">2.63</td>
<td style="text-align: center;">3.31</td>
<td style="text-align: center;">2.47</td>
<td style="text-align: center;">3.49</td>
</tr>
<tr class="even">
<td style="text-align: center;">2026-01-01</td>
<td style="text-align: center;">3.73</td>
<td style="text-align: center;">3.30</td>
<td style="text-align: center;">4.15</td>
<td style="text-align: center;">3.09</td>
<td style="text-align: center;">4.39</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2026-02-01</td>
<td style="text-align: center;">3.82</td>
<td style="text-align: center;">3.39</td>
<td style="text-align: center;">4.26</td>
<td style="text-align: center;">3.19</td>
<td style="text-align: center;">4.47</td>
</tr>
<tr class="even">
<td style="text-align: center;">2026-03-01</td>
<td style="text-align: center;">3.39</td>
<td style="text-align: center;">3.01</td>
<td style="text-align: center;">3.77</td>
<td style="text-align: center;">2.79</td>
<td style="text-align: center;">3.98</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>En esta sección se detalla los valores proyectados para el período octubre 2025 a marzo 2026 con sus respectivos intervalos al 80 y 95% de confianza.</p>
<p>El valor máximo proyectado corresponde a febrero de 2026, con una tasa de 3,82%, mientras que el mínimo se registra en diciembre de 2025, con 2,97%. La media del periodo proyectado se sitúa en 3,49%, con una desviación estándar de 0,30%, lo que refleja una variabilidad moderada en las estimaciones. Asimismo, se observa que las proyecciones se mantienen por debajo de los máximos y promedios históricos, siempre que las condiciones económicas permanezcan estables y no se introduzcan medidas de política gubernamental que puedan alterar la dinámica del mercado laboral. En caso de que se implementen nuevas políticas, el comportamiento de la serie y sus proyecciones podría modificarse significativamente.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>